`timescale 1ns/1ps 
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Dec 12 2023 12:11:59 WET (Dec 12 2023 12:11:59 UTC)

// Verification Directory fv/circuito09 

module circuito09_scan_syn(clk, reset, emptyID1, emptyID2, emptyID1_prev,
     emptyID2_prev, start_test, end_test, end_test_global, clearID1,
     clearID2, restart_col_select, loadID1, loadID2, resetID1,
     resetID2, clearID1_prev, clearID2_prev, scan_en, scan_in,
     scan_out);
  input clk, reset, emptyID1, emptyID2, emptyID1_prev, emptyID2_prev,
       start_test, end_test, end_test_global, scan_en, scan_in;
  output clearID1, clearID2, restart_col_select, loadID1, loadID2,
       resetID1, resetID2, clearID1_prev, clearID2_prev, scan_out;
  wire clk, reset, emptyID1, emptyID2, emptyID1_prev, emptyID2_prev,
       start_test, end_test, end_test_global, scan_en, scan_in;
  wire clearID1, clearID2, restart_col_select, loadID1, loadID2,
       resetID1, resetID2, clearID1_prev, clearID2_prev, scan_out;
  wire [3:0] cntCh1_prev;
  wire [3:0] cntCh1;
  wire [3:0] cntCh2_prev;
  wire [3:0] cntCh2;
  wire [1:0] cur;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_58, n_61;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97;
  DFS1 \cntCh1_prev_reg[3] (.C (clk), .D (n_96), .SD (n_13), .SE
       (scan_en), .Q (cntCh1_prev[3]), .QN (n_17));
  DFS1 \cntCh1_reg[3] (.C (clk), .D (n_95), .SD (n_11), .SE (scan_en),
       .Q (cntCh1[3]), .QN (n_16));
  DFS1 \cntCh2_prev_reg[3] (.C (clk), .D (n_94), .SD (n_12), .SE
       (scan_en), .Q (cntCh2_prev[3]), .QN (n_15));
  DFS1 \cntCh2_reg[3] (.C (clk), .D (n_97), .SD (n_10), .SE (scan_en),
       .Q (cntCh2[3]), .QN (n_14));
  DFS1 \cntCh1_prev_reg[2] (.C (clk), .D (n_83), .SD (n_7), .SE
       (scan_en), .Q (cntCh1_prev[2]), .QN (n_13));
  DFS1 \cntCh2_prev_reg[2] (.C (clk), .D (n_91), .SD (n_8), .SE
       (scan_en), .Q (cntCh2_prev[2]), .QN (n_12));
  DFS1 \cntCh1_reg[2] (.C (clk), .D (n_93), .SD (n_6), .SE (scan_en),
       .Q (cntCh1[2]), .QN (n_11));
  DFS1 \cntCh2_reg[2] (.C (clk), .D (n_89), .SD (n_5), .SE (scan_en),
       .Q (cntCh2[2]), .QN (n_10));
  NOR21 g1779__2398(.A (n_88), .B (n_87), .Q (n_97));
  NOR21 g1780__5107(.A (n_82), .B (n_86), .Q (n_96));
  NOR21 g1781__6260(.A (n_92), .B (n_85), .Q (n_95));
  NOR21 g1782__4319(.A (n_90), .B (n_84), .Q (n_94));
  DFS1 \cur_reg[0] (.C (clk), .D (n_77), .SD (n_14), .SE (scan_en), .Q
       (n_9), .QN (restart_col_select));
  NOR21 g1792__8428(.A (n_92), .B (n_78), .Q (n_93));
  NOR21 g1793__5526(.A (n_90), .B (n_81), .Q (n_91));
  NOR21 g1794__6783(.A (n_88), .B (n_80), .Q (n_89));
  DFS1 \cntCh2_prev_reg[1] (.C (clk), .D (n_68), .SD (n_2), .SE
       (scan_en), .Q (cntCh2_prev[1]), .QN (n_8));
  DFS1 \cntCh1_prev_reg[1] (.C (clk), .D (n_65), .SD (n_3), .SE
       (scan_en), .Q (cntCh1_prev[1]), .QN (n_7));
  DFS1 \cntCh1_reg[1] (.C (clk), .D (n_67), .SD (n_1), .SE (scan_en),
       .Q (cntCh1[1]), .QN (n_6));
  XNR21 g1789__3680(.A (cntCh2[3]), .B (n_69), .Q (n_87));
  XNR21 g1788__1617(.A (cntCh1_prev[3]), .B (n_75), .Q (n_86));
  XNR21 g1787__2802(.A (cntCh1[3]), .B (n_73), .Q (n_85));
  XNR21 g1790__1705(.A (cntCh2_prev[3]), .B (n_71), .Q (n_84));
  NOR21 g1791__5122(.A (n_82), .B (n_79), .Q (n_83));
  DFS1 \cntCh2_reg[1] (.C (clk), .D (n_66), .SD (n_0), .SE (scan_en),
       .Q (cntCh2[1]), .QN (n_5));
  DFS1 \cur_reg[1] (.C (clk), .D (n_53), .SD (n_9), .SE (scan_en), .Q
       (cur[1]), .QN (scan_out));
  INV3 g1798(.A (n_72), .Q (n_81));
  INV3 g1797(.A (n_70), .Q (n_80));
  INV3 g1795(.A (n_76), .Q (n_79));
  INV3 g1796(.A (n_74), .Q (n_78));
  AOI211 g1806__8246(.A (n_52), .B (n_35), .C (reset), .Q (n_77));
  DFS1 \cntCh1_prev_reg[0] (.C (clk), .D (n_45), .SD (scan_in), .SE
       (scan_en), .Q (cntCh1_prev[0]), .QN (n_3));
  DFS1 \cntCh2_prev_reg[0] (.C (clk), .D (n_46), .SD (n_16), .SE
       (scan_en), .Q (cntCh2_prev[0]), .QN (n_2));
  DFS1 \cntCh1_reg[0] (.C (clk), .D (n_47), .SD (n_17), .SE (scan_en),
       .Q (cntCh1[0]), .QN (n_1));
  DFS1 \cntCh2_reg[0] (.C (clk), .D (n_44), .SD (n_15), .SE (scan_en),
       .Q (cntCh2[0]), .QN (n_0));
  ADD22 g1799__7098(.A (n_38), .B (cntCh1_prev[2]), .CO (n_75), .S
       (n_76));
  ADD22 g1800__6131(.A (n_36), .B (cntCh1[2]), .CO (n_73), .S (n_74));
  ADD22 g1802__1881(.A (n_42), .B (cntCh2_prev[2]), .CO (n_71), .S
       (n_72));
  ADD22 g1801__5115(.A (n_40), .B (cntCh2[2]), .CO (n_69), .S (n_70));
  NOR21 g1810__7482(.A (n_90), .B (n_49), .Q (n_68));
  NOR21 g1811__4733(.A (n_92), .B (n_51), .Q (n_67));
  NOR21 g1812__6161(.A (n_88), .B (n_48), .Q (n_66));
  NOR21 g1809__9315(.A (n_82), .B (n_50), .Q (n_65));
  NOR30 g1816__9945(.A (n_58), .B (cntCh1[3]), .C (cntCh1[1]), .Q
       (loadID1));
  OAI210 g1813__2883(.A (cntCh2[1]), .B (n_32), .C (n_61), .Q
       (clearID2));
  OAI210 g1821__2346(.A (cntCh1[1]), .B (n_31), .C (n_61), .Q
       (clearID1));
  NOR30 g1817__1666(.A (n_54), .B (cntCh2[3]), .C (cntCh2[1]), .Q
       (loadID2));
  NOR30 g1820__7410(.A (n_58), .B (n_18), .C (n_21), .Q (resetID1));
  OAI310 g1818__6417(.A (cntCh2_prev[0]), .B (cntCh2_prev[2]), .C
       (n_27), .D (n_61), .Q (clearID2_prev));
  OAI310 g1819__5477(.A (cntCh1_prev[0]), .B (cntCh1_prev[2]), .C
       (n_30), .D (n_61), .Q (clearID1_prev));
  NOR30 g1815__2398(.A (n_54), .B (n_23), .C (n_24), .Q (resetID2));
  NOR21 g1833__5107(.A (reset), .B (n_34), .Q (n_53));
  MUX22 g1834__6260(.A (n_33), .B (end_test), .S (n_61), .Q (n_52));
  INV3 g1824(.A (n_37), .Q (n_51));
  INV3 g1823(.A (n_39), .Q (n_50));
  INV3 g1822(.A (n_43), .Q (n_49));
  INV3 g1825(.A (n_41), .Q (n_48));
  NOR21 g1838__4319(.A (n_92), .B (cntCh1[0]), .Q (n_47));
  NOR21 g1837__8428(.A (n_90), .B (cntCh2_prev[0]), .Q (n_46));
  NOR21 g1836__5526(.A (n_82), .B (cntCh1_prev[0]), .Q (n_45));
  NOR21 g1839__6783(.A (n_88), .B (cntCh2[0]), .Q (n_44));
  ADD22 g1826__3680(.A (cntCh2_prev[1]), .B (cntCh2_prev[0]), .CO
       (n_42), .S (n_43));
  ADD22 g1829__1617(.A (cntCh2[1]), .B (cntCh2[0]), .CO (n_40), .S
       (n_41));
  ADD22 g1827__2802(.A (cntCh1_prev[1]), .B (cntCh1_prev[0]), .CO
       (n_38), .S (n_39));
  ADD22 g1828__1705(.A (cntCh1[1]), .B (cntCh1[0]), .CO (n_36), .S
       (n_37));
  OAI212 g1840__5122(.A (end_test_global), .B (n_61), .C (cur[1]), .Q
       (n_35));
  AOI211 g1843__8246(.A (n_61), .B (end_test), .C (cur[1]), .Q (n_34));
  NAND30 g1844__7098(.A (n_61), .B (n_20), .C (cntCh2[2]), .Q (n_54));
  NAND30 g1845__6131(.A (n_61), .B (n_19), .C (cntCh1[2]), .Q (n_58));
  NAND22 g1854__1881(.A (n_22), .B (start_test), .Q (n_33));
  NAND30 g1841__5115(.A (cntCh2[3]), .B (cntCh2[2]), .C (cntCh2[0]), .Q
       (n_32));
  NAND30 g1842__7482(.A (cntCh1[3]), .B (cntCh1[2]), .C (cntCh1[0]), .Q
       (n_31));
  CLKIN0 g1851(.A (n_26), .Q (n_82));
  CLKIN0 g1847(.A (n_28), .Q (n_92));
  CLKIN0 g1846(.A (n_29), .Q (n_88));
  CLKIN0 g1852(.A (n_25), .Q (n_90));
  NAND20 g1848__4733(.A (cntCh1_prev[3]), .B (cntCh1_prev[1]), .Q
       (n_30));
  NOR20 g1849__6161(.A (emptyID2), .B (reset), .Q (n_29));
  NOR20 g1850__9315(.A (emptyID1), .B (reset), .Q (n_28));
  NAND20 g1853__9945(.A (cntCh2_prev[3]), .B (cntCh2_prev[1]), .Q
       (n_27));
  NOR20 g1855__2883(.A (emptyID1_prev), .B (reset), .Q (n_26));
  NOR20 g1856__2346(.A (emptyID2_prev), .B (reset), .Q (n_25));
  INV0 g1859(.A (cntCh2[1]), .Q (n_24));
  INV0 g1862(.A (cntCh2[3]), .Q (n_23));
  INV2 g1861(.A (cur[1]), .Q (n_22));
  INV0 g1858(.A (cntCh1[1]), .Q (n_21));
  INV0 g1863(.A (cntCh2[0]), .Q (n_20));
  INV0 g1864(.A (cntCh1[0]), .Q (n_19));
  INV0 g1857(.A (cntCh1[3]), .Q (n_18));
  CLKIN3 g1860(.A (restart_col_select), .Q (n_61));
endmodule

